# This file has been generated by node2nix 1.11.1. Do not edit!

{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [ ],
}:

let
  sources = { };
in
{
  "@augmentcode/auggie" = nodeEnv.buildNodePackage {
    name = "_at_augmentcode_slash_auggie";
    packageName = "@augmentcode/auggie";
    version = "0.15.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@augmentcode/auggie/-/auggie-0.15.0.tgz";
      sha512 = "s6Yw3gpWItztICjx7GOIM7GTrfVadKMZCP0dlIsIVVb0dzUaY2pybEqxUMoaOuzf1vnrnd67Z2PoE3tmUsov0g==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Auggie CLI Client by Augment Code";
      homepage = "https://augmentcode.com";
      license = "SEE LICENSE IN LICENSE.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@openai/codex" = nodeEnv.buildNodePackage {
    name = "_at_openai_slash_codex";
    packageName = "@openai/codex";
    version = "0.93.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@openai/codex/-/codex-0.93.0.tgz";
      sha512 = "3skVlzRN3bApbyCX3zeEK6umGb4OfaTa/lsuJ9syng+NxUGptDMFsrOoC+rMU1uYeFtt+OjYttjpfHY2xE1DAQ==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "<p align=\"center\"><code>npm i -g @openai/codex</code><br />or <code>brew install --cask codex</code></p> <p align=\"center\"><strong>Codex CLI</strong> is a coding agent from OpenAI that runs locally on your computer. <p align=\"center\">   <img src=\"./.githu";
      homepage = "https://github.com/openai/codex#readme";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
